Check git tag

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -8,9 +8,28 @@ on:
 
 jobs:
 
+  check-version:
+    name: Check git tag
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v7
+
+      - name: Ensure git tag corresponds to project version
+        run: |
+          project_version="$(tr -d '[:space:]' < VERSION.txt)"
+          echo "Git tag = [$GITHUB_REF_NAME]"
+          echo "Project version = [$project_version]"
+          if [ "$GITHUB_REF_NAME" != "v$project_version" ]; then
+            echo "Mismatch between git tag and project version (VERSION.txt), aborting deployment..."
+            exit 1
+          fi
+
   build-wheels:
     name: Build wheels (${{ matrix.os }})
     runs-on: ${{ matrix.os }}
+    needs:
+      - check-version
 
     strategy:
       fail-fast: false
@@ -42,6 +61,8 @@ jobs:
   build-sdist:
     name: Build source distribution
     runs-on: ubuntu-latest
+    needs:
+      - check-version
 
     steps:
       - uses: actions/checkout@v7
@@ -64,6 +85,7 @@ jobs:
     name: Publish to PyPI
     runs-on: ubuntu-latest
     needs:
+      - check-version
       - build-wheels
       - build-sdist
     # TODO keep? if: github.event_name == 'release'
